Remove Visit and its Location in a single problem fact change
When removing any location on the map, solver fails with:

java.lang.IllegalStateException: The supply (ExternalizedSingletonInverseVariableSupply(previousStandstill))
is corrupted, because the entity (Visit-5) for sourceVariable (previousStandstill)
cannot be inserted: another entity (Visit-5) already has that value (Visit-6).
	at org.optaplanner.core.impl.domain.variable.inverserelation.ExternalizedSingletonInverseVariableSupply.insert(ExternalizedSingletonInverseVariableSupply.java:100)
	at org.optaplanner.core.impl.domain.variable.inverserelation.ExternalizedSingletonInverseVariableSupply.afterVariableChanged(ExternalizedSingletonInverseVariableSupply.java:78)
	at org.optaplanner.core.impl.domain.variable.listener.support.VariableListenerSupport.triggerVariableListenersInNotificationQueues(VariableListenerSupport.java:209)
	at org.optaplanner.core.impl.score.director.AbstractScoreDirector.triggerVariableListeners(AbstractScoreDirector.java:258)